### PR TITLE
run eslint and test via Travis

### PR DESCRIPTION
**Pull request by glasser**
Make all code pass eslint with slight variants on the AirBNB style
guide.

### CODE REVIEW

**Comment by glasser** [comment]
One difficult-to-review bit: I reordered a bunch of Report.js to stop places where you called functions before they were defined.  let/const have this "temporal dead zone" thing where definitions are sort of hoisted and sort of not.  I think it might be the case that the code there is legit (because you probably don't call any functions until the whole file is evaluated) but hey, eslint didn't like it, and ordering things with "define before use" seems reasonable to me.

**Comment by n1mmy** [comment]
"define before use" seems reasonable to me too. The order there was pure personal aesthetic as I didn't think it mattered -- nothing there should be called until well after everything is loaded. I still prefer your version though, I think a consistent functional order is better than a personal aesthetic order even if it is not technically necessary in this case =)

**Comment by glasser** [comment]
Great! I hope you noticed that Travis tests don't appear to run on Node 4 right now: if our goal is to ensure the agent runs on Node 4, we should file a bug and look into that.

By the way, my personal preference unless there is a huge hurry (eg if you need to refactor soon) is to merge my own PRs after approval, since I often think of further changes that need to be made while review is happening.

**Comment by n1mmy** [comment]
Yeah, we should support at least Node 4 or 6, and at least graphql 0.6 and 0.7.

Re merging, gotcha, will not merge PRs unless there is a hurry. Thanks for letting me know.

**Pull request merged**
